global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Target: node_exporter container
        

rule_files:
  - "alert.rules.yml"   # Load alert rules from file

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'   # Forward alerts to Alertmanager
